# Load Dataset

In [8]:
import pandas as pd

ai4i = pd.read_csv(r'C:\Users\anast\OneDrive\Desktop\DSML\data\ai4i2020.csv')
AI4I = pd.read_csv(r'C:\Users\anast\OneDrive\Desktop\DSML\data\AI4I_Professional_IoT_Maintenance_Features (2).csv')

df = pd.merge(ai4i,AI4I, on = "UDI" , how="inner")
df.to_csv("AI4I_combined_dataset",index=False)

# Dataset overview

In [10]:
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,...,RNF,Machine_Age_Years,Operating_Hours,Days_Since_Last_Maintenance,Maintenance_Count_Last_Year,Energy_Consumption_kWh,Vibration_Level_mm_s,Humidity_Percent,Ambient_Dust_Level_ug_m3,Maintenance_Cost_USD
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,...,0,3,3864,315,0,57.29,1.38,64.4,11.5,185.82
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,...,0,2,3884,365,1,56.50,0.50,51.3,29.3,265.44
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,...,0,4,2817,357,1,68.59,1.01,73.3,30.6,323.02
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,...,0,5,5887,339,2,57.81,0.63,42.9,24.9,609.14
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,...,0,1,2849,347,0,46.00,2.66,34.8,12.8,50.00

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   UDI                          10000 non-null  int64
 1   Product ID                   10000 non-null  str
 2   Type                         10000 non-null  str
 3   Air temperature [K]          10000 non-null  float64
 4   Process temperature [K]      10000 non-null  float64
 5   Rotational speed [rpm]       10000 non-null  int64
 6   Torque [Nm]                  10000 non-null  float64
 7   Tool wear [min]              10000 non-null  int64
 8   Machine failure              10000 non-null  int64
 9   TWF                          10000 non-null  int64
 10  HDF                          10000 non-null  int64
 11  PWF                          10000 non-null  int64
 12  OSF                          10000 non-null  int64
 13  RNF                          10000 non-null  int64
 14  Machine_Age_Years            10000 non-null  int64
 15  Operating_Hours              10000 non-null  int64
 16  Days_Since_Last_Maintenance  10000 non-null  int64
 17  Maintenance_Count_Last_Year  10000 non-null  int64
 18  Energy_Consumption_kWh       10000 non-null  float64
 19  Vibration_Level_mm_s         10000 non-null  float64
 20  Humidity_Percent             10000 non-null  float64
 21  Ambient_Dust_Level_ug_m3     10000 non-null  float64
 22  Maintenance_Cost_USD         10000 non-null  float64
dtypes: float64(8), int64(13), str(2)
memory usage: 1.8 MB

In [12]:
df.describe()

,UDI,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,...,RNF,Machine_Age_Years,Operating_Hours,Days_Since_Last_Maintenance,Maintenance_Count_Last_Year,Energy_Consumption_kWh,Vibration_Level_mm_s,Humidity_Percent,Ambient_Dust_Level_ug_m3,Maintenance_Cost_USD
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,...,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,300.004930,310.005560,1538.776100,39.986910,107.951000,0.033900,0.004600,0.011500,0.009500,...,0.00190,8.370900,14935.747500,234.951900,5.53050,58.968306,3.766053,55.155770,36.624850,998.82742
std,2886.89568,2.000259,1.483734,179.284096,9.968934,63.654147,0.180981,0.067671,0.106625,0.097009,...,0.04355,3.467468,7017.024349,80.023921,2.69492,8.399636,1.737343,11.864233,10.533679,462.39413
min,1.00000,295.300000,305.700000,1168.000000,3.800000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,1.000000,500.000000,1.000000,0.00000,31.410000,0.500000,30.000000,5.000000,50.00000
25%,2500.75000,298.300000,308.800000,1423.000000,33.200000,53.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,6.000000,9172.000000,171.000000,3.00000,53.090000,2.330000,46.900000,29.400000,636.67250
50%,5000.50000,300.100000,310.100000,1503.000000,40.100000,108.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,8.000000,14890.000000,237.000000,6.00000,58.530000,3.750000,55.000000,36.600000,996.54000
75%,7500.25000,301.500000,311.100000,1612.000000,46.800000,162.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,11.000000,20672.500000,302.000000,8.00000,64.630000,5.100000,63.200000,43.800000,1365.98250
max,10000.00000,304.500000,313.800000,2886.000000,76.600000,253.000000,1.000000,1.000000,1.000000,1.000000,...,1.00000,15.000000,31848.000000,365.000000,12.00000,97.760000,9.780000,90.000000,74.100000,2206.27000

In [ ]:
df.isnull().sum()

UDI                            0
Product ID                     0
Type                           0
Air temperature [K]            0
Process temperature [K]        0
Rotational speed [rpm]         0
Torque [Nm]                    0
Tool wear [min]                0
Machine failure                0
TWF                            0
HDF                            0
PWF                            0
OSF                            0
RNF                            0
Machine_Age_Years              0
Operating_Hours                0
Days_Since_Last_Maintenance    0
Maintenance_Count_Last_Year    0
Energy_Consumption_kWh         0
Vibration_Level_mm_s           0
Humidity_Percent               0
Ambient_Dust_Level_ug_m3       0
Maintenance_Cost_USD           0
dtype: int64

# Exploratory data analysis visualizations

In [ ]:
import matplotlib

:

: